In [ ]:
import pandas as pd
import numpy as np
import re

Príprava SlovakSA

In [ ]:
from google.colab import userdata
userdata.get('HuggingFace')

'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'

In [ ]:
splits = {'train': 'train.csv', 'validation': 'dev.csv', 'test': 'test.csv'}
sa = pd.read_csv("hf://datasets/DGurgurov/slovak_sa/" + splits["train"])
sa.head()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

   label                                               text
0      1  Bola ústretová,milá a komunikatívna .Šikovná s...
1      1                         dobrá obsluha, pekná baba.
2      1              Prijemne vystupovanie, ochota  pomôcť
3      1                                          Za ochotu
4      1          Ďakujem za rýchle vybavenie a ústretovosť

spojíme train a dev časti datasetu do jedného celku

In [ ]:
splits = {
    "train": "train.csv",
    "validation": "dev.csv"
}

sa = pd.concat(
    [
        pd.read_csv(f"hf://datasets/DGurgurov/slovak_sa/{fname}")
        for fname in splits.values()
    ], ignore_index=True
)
print(sa.shape)
sa.head()

(4082, 2)

   label                                               text
0      1  Bola ústretová,milá a komunikatívna .Šikovná s...
1      1                         dobrá obsluha, pekná baba.
2      1              Prijemne vystupovanie, ochota  pomôcť
3      1                                          Za ochotu
4      1          Ďakujem za rýchle vybavenie a ústretovosť

Príprava Slovníka

načítame slovník a vytvoríme z neho dataframe

In [ ]:
file_path = "SentiWordNet_3.0.0_SK.txt"

rows = []
with open(file_path, "r", encoding="utf-8") as f:
    for line in f:
        if not line.strip() or line.startswith("#"): #skip lines containing comments
            continue

        parts = line.rstrip("\n").split("\t", maxsplit=5) #split lines 5 times

        if len(parts) == 5: #if gloss is missing
            pos, sid, pos_score, neg_score, synset_terms = parts
            gloss = ""
        elif len(parts) == 6: #gloss is present
            pos, sid, pos_score, neg_score, synset_terms, gloss = parts
        else:
            #safety check
            continue

        pol = float(pos_score) - float(neg_score) #calculate word polarity

        for tok in synset_terms.split():
            word = tok.rsplit("#", 1)[0].lower() #split sense numbers
            rows.append((word, pol))

lex_df = pd.DataFrame(rows, columns=["word", "polarity"]) #create a dataframe using extracted rows
word_lex = lex_df.groupby("word", as_index=False)["polarity"].mean() #group matching rows
lex_dict = dict(zip(word_lex["word"], word_lex["polarity"]))  #convert into dictionary

print("Lexicon words:", len(lex_dict))

Lexicon words: 134870

Vyhodnotenie (bez lematizácie) SlovakSA

In [ ]:
#regex to define allowed symbols. We exclude emojis, punctuation,..
token_re = re.compile(r"[0-9A-Za-zÁÄČĎÉÍĹĽŇÓÔŔŠŤÚÝŽáäčďéíĺľňóôŕšťúýž_]+")

def score_text(text):
    if not isinstance(text, str):
        return 0.0, 0

    #parse every token with regex
    toks = token_re.findall(text.lower())
    #find a match in lexicon and save values
    vals = [lex_dict[t] for t in toks if t in lex_dict]
    return (float(np.sum(vals)) if vals else 0.0), len(vals)

In [ ]:
#apply score_text
sa = sa.copy()
sa[["lex_score", "lex_hits"]] = sa["text"].apply(
    lambda t: pd.Series(score_text(t))
)

#evaluate results
print(sa[["lex_score", "lex_hits"]].describe())
print("Coverage (>=1 hit):", (sa["lex_hits"] > 0).mean())

         lex_score     lex_hits
count  3560.000000  3560.000000
mean      0.118780     5.142697
std       0.390057     6.844426
min      -2.040284     0.000000
25%      -0.055556     1.000000
50%       0.019444     3.000000
75%       0.286431     6.000000
max       3.425207    85.000000
Coverage (>=1 hit): 0.9078651685393259

Pokrytie lexikónom: ~90 % textov obsahuje aspoň jedno sentimentovo ohodnotené slovo

Priemerný počet slov (lex_hits): 5 slov na text

Hodnota sentimentu bola zachovaná aj po preklade

In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

#actual sentiment values
y_true = sa["label"].astype(int).values

#binary prediction
y_pred = (sa["lex_score"] > 0).astype(int).values

#calculate metrics accuracy, precision, recall, F1 score
acc = accuracy_score(y_true, y_pred)
prec, rec, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="binary", zero_division=0
)
cm = confusion_matrix(y_true, y_pred)

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1:", f1)
print("Confusion matrix [[TN FP], [FN TP]]:\n", cm)

Accuracy: 0.5938202247191011
Precision: 0.9220085470085471
Recall: 0.5703899537343027
F1: 0.7047774601878317
Confusion matrix [[TN FP], [FN TP]]:
 [[ 388  146]
 [1300 1726]]

Accuracy: ~0.59: Nízka informatívnosť (konzervatívne predikcie)

Precision: ~0.92: Veľmi vysoká presnosť pozitívnych predikcií

Recall: ~0.57: Zachytená približne polovica pozitívnych textov

Lexikón vykazuje vysokú spoľahlivosť pozitívnych predikcií, čo je očakávané, keďže trénovací dataset obsahuje prevažne pozitívne príklady.

Lexikón sme testovali na dátach SlovakSA bez lematizácie.

Vyhodnotie (lematizácia) SlovakSA

In [ ]:
!pip -q install stanza

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 21.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 39.8 MB/s eta 0:00:00

In [ ]:
import stanza
stanza.download("sk", verbose=False)

#initialize stanza tokenizer
nlp = stanza.Pipeline(
    lang="sk",
    processors="tokenize,pos,lemma",
    tokenize_no_ssplit=True,
    use_gpu=True,
    verbose=False
)

In [ ]:
def score_text_lemma(text: str):
    if not isinstance(text, str) or not text.strip():
        return 0.0, 0

    #lemmatize tokens
    doc = nlp(text)
    lemmas = []
    for sent in doc.sentences:
        for w in sent.words:
            if w.lemma:
                lemmas.append(w.lemma.lower().replace(" ", "_"))

    #save and sum values
    vals = [lex_dict[l] for l in lemmas if l in lex_dict]
    score = float(np.sum(vals)) if vals else 0.0
    return score, len(vals)

In [ ]:
#apply score_text_lemma to temporary df
tmp = sa["text"].apply(lambda t: pd.Series(score_text_lemma(t)))
sa = sa.copy()
sa["lex_score_lemma"] = tmp[0]
sa["lex_hits_lemma"] = tmp[1]

coverage = (sa["lex_hits_lemma"] > 0).mean()

#binary clasification
y_true = sa["label"].astype(int).values
y_pred = (sa["lex_score_lemma"] > 0).astype(int).values

#calculate metrics
acc = accuracy_score(y_true, y_pred)
prec, rec, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="binary", zero_division=0)
cm = confusion_matrix(y_true, y_pred)

print("Coverage (>=1 hit):", coverage)
print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1:", f1)
print("Confusion matrix [[TN FP],[FN TP]]:\n", cm)

Coverage (>=1 hit): 0.9452247191011236
Accuracy: 0.7002808988764045
Precision: 0.9166312207571247
Recall: 0.7121612690019828
F1: 0.801562209410452
Confusion matrix [[TN FP],[FN TP]]:
 [[ 338  196]
 [ 871 2155]]

Coverage 0.94: Takmer všetky texty majú aspoň jeden zásah lexikónu

Accuracy 0.70: výrazne vyššia ako bez lematizácie

Precision ~0.92: Pozitívne predikcie sú spoľahlivé, minimum FP

Recall ~0.71: Zachytáva podstatne viac pozitívnych textov než bez lematizácie

Na základe porovnania môžeme s istotou povedať, že lematizácia datasetu SlovakSA má pozitívny vplyv na lexikálnu klasifikáciu, čo je aj očakávané

Analýza chýb lexikónu

In [ ]:
sa = sa.copy()

sa["y_true"] = sa["label"].astype(int)
sa["y_pred"] = (sa["lex_score_lemma"] > 0).astype(int)

sa["error_type"] = "correct"
sa.loc[(sa["y_pred"] == 1) & (sa["y_true"] == 0), "error_type"] = "FP"
sa.loc[(sa["y_pred"] == 0) & (sa["y_true"] == 1), "error_type"] = "FN"

sa["error_type"].value_counts()

error_type
correct    2493
FN          871
FP          196
Name: count, dtype: int64

Vidíme, že lexikón sa mýli hlavne v negatívnej klasifikácii, čo môže byť spôsobené napríklad sarkazmom. Lexikón zachytáva takmer všetok pozitívny sentiment. Testovaním sme dokázali, že vytvorený lexikón je vhodný na klasifikáciu sentimentu v slovenskom jazyku.

Pri ďaľšej časti práce, kde rozšírime model RoBERTa o lexikálnu klasifikáciu, očakávame, že presnosť v klasifikácii sa výrazne zvýši, hlavne vďaka kontextu, ktorý nám model dodá.